import {useState,useRef} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {request} from '@/lib/api';
import type {Community,Outing} from './types';
export function Outings({data,reload}:{data:Community;reload:()=>Promise<void>}) {
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[drag,setDrag]=useState<number|null>(null);const dragRef=useRef<{trip:string;index:number}|null>(null);
 async function action(path:string,method:string,payload:any){setError('');setBusy(true);try{await request(path,method,payload);await reload();return true;}catch(e){setError((e as Error).message);await reload();return false;}finally{setBusy(false);}}
 const save=(t:Outing,stops:string[],name=t.name)=>action('/api/community/outings/'+t.id,'PUT',{stops,name,revision:t.revision});
 function move(t:Outing,from:number,to:number){if(from===to||to<0||to>=t.stops.length)return;const arr=[...t.stops];arr.splice(to,0,arr.splice(from,1)[0]!);void save(t,arr);}
 return <section><h1>Plan a food outing</h1><p>Choose reviewed restaurants, save their locations and put your stops in order.</p><form className="control-row" onSubmit={e=>{e.preventDefault();const f=e.currentTarget;void action('/api/community/outings','POST',{name:new FormData(f).get('name')}).then(ok=>{if(ok)f.reset();});}}><Input required name="name" placeholder="Saturday food walk" maxLength={100}/><Button disabled={busy}>Create plan</Button></form>
 {error&&<p className="notice-error" role="alert">{error}</p>}{!data.outings.length&&<p className="empty-state">Create your first outing, then add a restaurant from the list.</p>}
 {data.outings.map(t=><article className="outing-card" key={t.id}><form className="control-row" onSubmit={e=>{e.preventDefault();void save(t,t.stops,String(new FormData(e.currentTarget).get('name')));}}><Input key={t.name} aria-label="Outing name" name="name" defaultValue={t.name} required maxLength={100}/><Button variant="outline" disabled={busy}>Rename</Button><Button type="button" variant="ghost" disabled={busy} onClick={()=>{if(confirm('Delete this outing plan?'))void action('/api/community/outings/'+t.id,'DELETE',undefined);}}>Delete</Button></form>
 <label>Add a restaurant<select disabled={busy} value="" onChange={e=>{if(e.target.value)void save(t,[...t.stops,e.target.value]);}}><option value="">Select a reviewed restaurant…</option>{data.restaurants.filter(r=>!t.stops.includes(r.id)).map(r=><option key={r.id} value={r.id}>{r.name} — {r.address}</option>)}</select></label>
 <p className="fineprint">Drag the ↕ handle to reorder. The ↑ and ↓ buttons work with keyboard and touch.</p>
 <ol className="stop-list">{t.stops.map((id,index)=>{const r=data.restaurants.find(x=>x.id===id);const pin=r?.lat!=null&&r.lng!=null?`${r.lat},${r.lng}`:r?`${r.name} ${r.address}`:'';return <li key={id} data-stop-index={index} data-trip={t.id} className={drag===index&&dragRef.current?.trip===t.id?'dragging':''}><button type="button" className="drag-handle" aria-label={`Drag stop ${index+1}`} disabled={busy} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);dragRef.current={trip:t.id,index};setDrag(index);}} onPointerUp={e=>{const active=dragRef.current;const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-stop-index]');if(active?.trip===t.id&&target?.getAttribute('data-trip')===t.id)move(t,active.index,Number(target.getAttribute('data-stop-index')));dragRef.current=null;setDrag(null);}} onPointerCancel={()=>{dragRef.current=null;setDrag(null);}}>↕</button><div className="stop-details"><strong>{index+1}. {r?.name||'Restaurant no longer available'}</strong><p>{r?.address||'Remove this stop before saving changes.'}</p>{r&&<a href={'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(pin)} target="_blank" rel="noreferrer">Open saved location ↗</a>}{r?.lat!=null&&<small>{r.lat.toFixed(5)}, {r.lng?.toFixed(5)}</small>}</div><div className="stop-actions"><Button variant="outline" disabled={busy||index===0} aria-label="Move up" onClick={()=>move(t,index,index-1)}>↑</Button><Button variant="outline" disabled={busy||index===t.stops.length-1} aria-label="Move down" onClick={()=>move(t,index,index+1)}>↓</Button><Button variant="ghost" disabled={busy} onClick={()=>void save(t,t.stops.filter(x=>x!==id))}>Remove</Button></div></li>;})}</ol>
 {!t.stops.length&&<p>No stops yet.</p>}
 </article>)}</section>;
}
