import { useState } from 'react';
import { Image, MessageSquare, MapPin, BadgeCheck, ArrowUpRight } from 'lucide-react';
import { request } from '@/lib/api';
export function Landing() {
 const [message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 return <div className="landing"><header><a className="brand" href="/">DishSpot</a><a className="black-button" href="/signup">Sign up</a></header>
 <main className="landing-hero"><div><h1>The dish comes first, not the restaurant</h1><p>Find dishes people have actually reviewed. See what they paid, read their experience and plan your next food outing.</p><ul>{[[Image,'Real dish photos and food-vlog links'],[MessageSquare,'Avoid, should try or must try'],[BadgeCheck,'Actual prices shared by the community'],[MapPin,'Reviewed places near your chosen location']].map(([Icon,label]:any)=><li key={label}><Icon size={20}/>{label}</li>)}</ul><div className="landing-actions"><a className="outline-button" href="/explore">Explore food</a><a href="/review">Write a review <ArrowUpRight size={20}/></a></div></div><div className="landing-art" role="img" aria-label="Illustrated sunlit restaurant"/></main>
 <footer><div><a className="brand" href="/">DishSpot</a><p>© 2026 DishSpot. Local test application.</p><div className="footer-links"><a href="/privacy">Privacy Policy</a><a href="/terms">Terms of Service</a><a href="/login">Log in</a></div></div><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{const data=new FormData(e.currentTarget);const r:any=await request('/api/newsletter','POST',{email:data.get('email'),consent:data.get('consent')==='on'});setMessage(r.message);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}><p>Join our newsletter to stay up to date on features and releases.</p><div className="newsletter"><input aria-label="Email for newsletter" name="email" type="email" placeholder="Enter your email" required/><button className="outline-button" disabled={busy}>{busy?'Saving…':'Subscribe'}</button></div><label className="consent"><input required name="consent" type="checkbox"/> I agree to the Privacy Policy and consent to receive updates from DishSpot.</label><p role="status">{message}</p></form></footer></div>;
}
