/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as CreatorRouteImport } from './routes/creator'
import { Route as CreatorPlansRouteImport } from './routes/creator-plans'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OutingsRouteImport } from './routes/outings'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SignupUserRouteImport } from './routes/signup-user'
import { Route as SignupVloggerRouteImport } from './routes/signup-vlogger'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as VloggersIndexRouteImport } from './routes/vloggers.index'
import { Route as VloggersIdRouteImport } from './routes/vloggers.$id'
import { Route as DishesIdIndexRouteImport } from './routes/dishes.$id.index'
import { Route as DishesIdReviewsRouteImport } from './routes/dishes.$id.reviews'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorPlansRoute = CreatorPlansRouteImport.update({
  id: '/creator-plans',
  path: '/creator-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OutingsRoute = OutingsRouteImport.update({
  id: '/outings',
  path: '/outings',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupUserRoute = SignupUserRouteImport.update({
  id: '/signup-user',
  path: '/signup-user',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupVloggerRoute = SignupVloggerRouteImport.update({
  id: '/signup-vlogger',
  path: '/signup-vlogger',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const VloggersIndexRoute = VloggersIndexRouteImport.update({
  id: '/vloggers/',
  path: '/vloggers/',
  getParentRoute: () => rootRouteImport,
} as any)
const VloggersIdRoute = VloggersIdRouteImport.update({
  id: '/vloggers/$id',
  path: '/vloggers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DishesIdIndexRoute = DishesIdIndexRouteImport.update({
  id: '/dishes/$id/',
  path: '/dishes/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const DishesIdReviewsRoute = DishesIdReviewsRouteImport.update({
  id: '/dishes/$id/reviews',
  path: '/dishes/$id/reviews',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/billing': typeof BillingRoute
  '/creator': typeof CreatorRoute
  '/creator-plans': typeof CreatorPlansRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/outings': typeof OutingsRoute
  '/people': typeof PeopleRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/review': typeof ReviewRoute
  '/saved': typeof SavedRoute
  '/signup': typeof SignupRoute
  '/signup-user': typeof SignupUserRoute
  '/signup-vlogger': typeof SignupVloggerRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/vloggers/$id': typeof VloggersIdRoute
  '/vloggers/': typeof VloggersIndexRoute
  '/dishes/$id/reviews': typeof DishesIdReviewsRoute
  '/dishes/$id/': typeof DishesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/billing': typeof BillingRoute
  '/creator': typeof CreatorRoute
  '/creator-plans': typeof CreatorPlansRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/outings': typeof OutingsRoute
  '/people': typeof PeopleRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/review': typeof ReviewRoute
  '/saved': typeof SavedRoute
  '/signup': typeof SignupRoute
  '/signup-user': typeof SignupUserRoute
  '/signup-vlogger': typeof SignupVloggerRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/vloggers/$id': typeof VloggersIdRoute
  '/vloggers': typeof VloggersIndexRoute
  '/dishes/$id/reviews': typeof DishesIdReviewsRoute
  '/dishes/$id': typeof DishesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/billing': typeof BillingRoute
  '/creator': typeof CreatorRoute
  '/creator-plans': typeof CreatorPlansRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/outings': typeof OutingsRoute
  '/people': typeof PeopleRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/review': typeof ReviewRoute
  '/saved': typeof SavedRoute
  '/signup': typeof SignupRoute
  '/signup-user': typeof SignupUserRoute
  '/signup-vlogger': typeof SignupVloggerRoute
  '/terms': typeof TermsRoute
  '/verify': typeof VerifyRoute
  '/vloggers/$id': typeof VloggersIdRoute
  '/vloggers/': typeof VloggersIndexRoute
  '/dishes/$id/reviews': typeof DishesIdReviewsRoute
  '/dishes/$id/': typeof DishesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/billing'
    | '/creator'
    | '/creator-plans'
    | '/explore'
    | '/forgot-password'
    | '/login'
    | '/outings'
    | '/people'
    | '/plans'
    | '/privacy'
    | '/profile'
    | '/review'
    | '/saved'
    | '/signup'
    | '/signup-user'
    | '/signup-vlogger'
    | '/terms'
    | '/verify'
    | '/vloggers/$id'
    | '/vloggers/'
    | '/dishes/$id/reviews'
    | '/dishes/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/billing'
    | '/creator'
    | '/creator-plans'
    | '/explore'
    | '/forgot-password'
    | '/login'
    | '/outings'
    | '/people'
    | '/plans'
    | '/privacy'
    | '/profile'
    | '/review'
    | '/saved'
    | '/signup'
    | '/signup-user'
    | '/signup-vlogger'
    | '/terms'
    | '/verify'
    | '/vloggers/$id'
    | '/vloggers'
    | '/dishes/$id/reviews'
    | '/dishes/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/billing'
    | '/creator'
    | '/creator-plans'
    | '/explore'
    | '/forgot-password'
    | '/login'
    | '/outings'
    | '/people'
    | '/plans'
    | '/privacy'
    | '/profile'
    | '/review'
    | '/saved'
    | '/signup'
    | '/signup-user'
    | '/signup-vlogger'
    | '/terms'
    | '/verify'
    | '/vloggers/$id'
    | '/vloggers/'
    | '/dishes/$id/reviews'
    | '/dishes/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BillingRoute: typeof BillingRoute
  CreatorRoute: typeof CreatorRoute
  CreatorPlansRoute: typeof CreatorPlansRoute
  ExploreRoute: typeof ExploreRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OutingsRoute: typeof OutingsRoute
  PeopleRoute: typeof PeopleRoute
  PlansRoute: typeof PlansRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ReviewRoute: typeof ReviewRoute
  SavedRoute: typeof SavedRoute
  SignupRoute: typeof SignupRoute
  SignupUserRoute: typeof SignupUserRoute
  SignupVloggerRoute: typeof SignupVloggerRoute
  TermsRoute: typeof TermsRoute
  VerifyRoute: typeof VerifyRoute
  VloggersIdRoute: typeof VloggersIdRoute
  VloggersIndexRoute: typeof VloggersIndexRoute
  DishesIdReviewsRoute: typeof DishesIdReviewsRoute
  DishesIdIndexRoute: typeof DishesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator-plans': {
      id: '/creator-plans'
      path: '/creator-plans'
      fullPath: '/creator-plans'
      preLoaderRoute: typeof CreatorPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outings': {
      id: '/outings'
      path: '/outings'
      fullPath: '/outings'
      preLoaderRoute: typeof OutingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup-user': {
      id: '/signup-user'
      path: '/signup-user'
      fullPath: '/signup-user'
      preLoaderRoute: typeof SignupUserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup-vlogger': {
      id: '/signup-vlogger'
      path: '/signup-vlogger'
      fullPath: '/signup-vlogger'
      preLoaderRoute: typeof SignupVloggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vloggers/': {
      id: '/vloggers/'
      path: '/vloggers'
      fullPath: '/vloggers/'
      preLoaderRoute: typeof VloggersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vloggers/$id': {
      id: '/vloggers/$id'
      path: '/vloggers/$id'
      fullPath: '/vloggers/$id'
      preLoaderRoute: typeof VloggersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dishes/$id/': {
      id: '/dishes/$id/'
      path: '/dishes/$id'
      fullPath: '/dishes/$id/'
      preLoaderRoute: typeof DishesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dishes/$id/reviews': {
      id: '/dishes/$id/reviews'
      path: '/dishes/$id/reviews'
      fullPath: '/dishes/$id/reviews'
      preLoaderRoute: typeof DishesIdReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BillingRoute: BillingRoute,
  CreatorRoute: CreatorRoute,
  CreatorPlansRoute: CreatorPlansRoute,
  ExploreRoute: ExploreRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OutingsRoute: OutingsRoute,
  PeopleRoute: PeopleRoute,
  PlansRoute: PlansRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ReviewRoute: ReviewRoute,
  SavedRoute: SavedRoute,
  SignupRoute: SignupRoute,
  SignupUserRoute: SignupUserRoute,
  SignupVloggerRoute: SignupVloggerRoute,
  TermsRoute: TermsRoute,
  VerifyRoute: VerifyRoute,
  VloggersIdRoute: VloggersIdRoute,
  VloggersIndexRoute: VloggersIndexRoute,
  DishesIdReviewsRoute: DishesIdReviewsRoute,
  DishesIdIndexRoute: DishesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
